package com.yakovliam.mygridbridge.station.device;

/**
 * The device manufacturer.
 *
 * @author Jacob C.
 */
public enum DeviceManufacturer {
  GENERAL_ELECTRIC, SIEMENS, SCHWEITZER_ENGINEERING_LABORATORIES, ABB_ITE_BBC, ALLEN_BRADLEY,
  BASLER, BECKWITH, BENDER, BOLTSWITCH, CROMPTON, E_MAX, ESTERLINE, FEDERAL_PACIFIC, HI_Z_CORP,
  LITTLEFUSE, OMRON, SQUARE_D, QUALITROL, SANGAMO, TAYLOR, TOSHIBA, WESTINGHOUSE_CUTLER_HAMMER,
  WHEELLOCK, WOODWARD, ALSTOM
}
