package com.yakovliam.mygridbridge.fault;

/**
 * The root cause of a fault.
 *
 * @author Jacob C.
 */
public enum FaultRootCause {
  LIGHTING_STRIKE, AGING_OF_CONDUCTOR, HEAVY_RAIN, HEAVY_WINDS, HEAVY_SNOW, ICE_ACCUMULATION,
  FALLING_TREE, FALLING_OBJECT, VEHICLE_ACCIDENT, EXCESSIVE_INTERNAL_CONDUCTOR_STRESSES,
  HIGH_CHANGES_ATMOSPHERIC_TEMPERATURES, BIRDS_PERCHING_ON_CONDUCTOR,
  ACCIDENTAL_CONTACT_WITH_CONDUCTOR, CHEMICAL_POLLUTION,

  // these would be nice to understand how to calculate using machine learning,
  // but we're simply not there yet
  ELECTRICAL_ARCING, CONDUCTOR_CORROSION, CONDUCTOR_DEGRADATION_DUE_TO_ELECTRICAL_STRESS,
  CONDUCTOR_DEGRADATION_DUE_TO_MECHANICAL_STRESS, CONDUCTOR_DEGRADATION_DUE_TO_THERMAL_STRESS,
  HUMAN_ERROR
}
